# Generated by Django 4.2 on 2023-05-14 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_address_customer_primary_phone_and_more'),
        ('store', '0003_alter_product_market_price_alter_product_our_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.CharField(choices=[('0.05', '5%'), ('0.10', '10%'), ('0.15', '15%'), ('0.18', '18%'), ('0.22', '22%')], default='0.05', max_length=10),
        ),
        migrations.AddField(
            model_name='productimage',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.customer')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product')),
            ],
        ),
    ]
